version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: rpgcore
      POSTGRES_USER: rpguser
      POSTGRES_PASSWORD: rpgpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  postgres_data: